import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// 문서 주소는 유지하고 탐색 목적에 따라 사이드바를 구성합니다.
const category = (label: string, dirName: string, slug: string) => ({
    type: 'category' as const,
    label,
    link: { type: 'generated-index' as const, slug },
    items: [{ type: 'autogenerated' as const, dirName }],
});

const sidebars: SidebarsConfig = {
    startupSidebar: [
        'startup/개요',
        'startup/install/필수-프로그램-설치하기',
        'startup/빠른-시작',
        { type: 'ref', id: 'tutorial/첫-조회' },
        { type: 'ref', id: 'guides/문제-해결' },
        {
            ...category('설치와 소스 빌드', 'startup/install', '/category/프로그램-설치'),
            items: [
                'startup/install/지원-운영체제',
                'startup/install/패키지-관리자-설치하기',
                'startup/install/자동-설치',
                'startup/install/개발-환경-설정하기',
                'startup/install/선택-프로그램-설치하기',
            ],
        },
    ],
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
    guidesSidebar: [
        { type: 'autogenerated', dirName: 'guides' },
        category('작업별 실습 모음', 'startup/handsonlab', '/category/hands-on-lab-따라하기'),
        { type: 'ref', label: '배포·운영 원칙 (12-Factors)', id: 'twelvefactor/Factors-란' },
    ],
    referenceSidebar: [
        'reference/index',
        'reference/거래-호출',
        'reference/식별자와-파일-경로',
        'startup/HandStack-CLI-사용법',
        category('서버·모듈·환경설정', 'reference/api', '/category/환경설정'),
        category('화면 라이브러리·UI 컨트롤', 'startup/learning', '/category/자습서-튜토리얼'),
    ],
    conceptSidebar: [
        'reference/concept/index',
        {
            ...category('구조와 설계', 'reference/concept', '/category/개념-및-관점'),
            items: [
                'reference/concept/계약-중심-거래',
                'reference/concept/데이터-게더링과-바인딩',
                'reference/concept/데이터베이스-연동',
                'reference/concept/모듈러-모놀리식-아키텍처',
                'reference/concept/In-process-Out-process-메시징',
                'reference/concept/서버리스-Function',
                'reference/concept/프로그램-다운타임-최소화-아이디어',
                'reference/concept/domain-driven-low-code-governance',
            ],
        },
    ],
    ideSidebar: [
        'ide/index',
        {
            type: 'category', label: '하나씩 익히기', collapsed: false,
            items: [
                'ide/learn/작업영역-열기',
                'ide/learn/프로젝트와-서버',
                'ide/learn/화면-편집하기',
                'ide/learn/계약-실행하기',
                'ide/learn/메뉴와-검증',
                'ide/learn/운영-인수인계',
            ],
        },
        {
            type: 'category', label: '필요할 때 확장하기',
            items: ['ide/guides/도메인-모델링', 'ide/guides/tabler-studio'],
        },
        {
            type: 'category', label: 'IDE 빠른 참조',
            link: { type: 'doc', id: 'ide/reference/index' },
            items: [
                'ide/reference/메뉴와-도구',
                'ide/reference/파일과-저장-규칙',
                'ide/reference/단축키',
                'ide/reference/설정과-보안',
                'ide/reference/문제-해결',
            ],
        },
    ],
    informationSidebar: [
        { type: 'autogenerated', dirName: 'information' },
        category('AI 활용 자료', 'reference/vide-coding-instruction', '/category/바이브-코딩-지침'),
        category('발표 자료', 'reference/presentation', '/category/강연세미나-문서'),
    ],
    // 이전 분류 URL을 유지합니다. 학습 메뉴는 각 주제의 소개 문서로 바로 연결합니다.
    legacyTutorialSidebar: [
        { type: 'category', label: '01. HandStack 기초 개념', link: { type: 'generated-index', slug: '/category/01-handstack-기초-개념', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/handstack-기초개념/index' }] },
        { type: 'category', label: '02. 프로젝트 구조와 파일 작업', link: { type: 'generated-index', slug: '/category/02-프로젝트-구조와-파일-작업', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/프로젝트구조와-파일작업/index' }] },
        { type: 'category', label: '03. 프로젝트와 개발 서버', link: { type: 'generated-index', slug: '/category/03-프로젝트와-개발-서버', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/프로젝트와-개발서버/index' }] },
        { type: 'category', label: '04. 도메인 모델과 데이터베이스', link: { type: 'generated-index', slug: '/category/04-도메인-모델과-데이터베이스', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/도메인모델과-데이터베이스/index' }] },
        { type: 'category', label: '05. 화면 저작 (HTML/JS 작성)', link: { type: 'generated-index', slug: '/category/05-화면-저작-htmljs-작성', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/화면저작/index' }] },
        { type: 'category', label: '06. 화면 동작과 거래 연결', link: { type: 'generated-index', slug: '/category/06-화면-동작과-거래-연결', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/화면동작과-거래연결/index' }] },
        { type: 'category', label: '07. dbclient SQL 계약', link: { type: 'generated-index', slug: '/category/07-dbclient-sql-계약', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/dbclient-SQL계약/index' }] },
        { type: 'category', label: '08. transact 거래 계약', link: { type: 'generated-index', slug: '/category/08-transact-거래-계약', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/transact-거래계약/index' }] },
        { type: 'category', label: '09. 확장 모듈', link: { type: 'generated-index', slug: '/category/09-확장-모듈', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/확장모듈/index' }] },
        { type: 'category', label: '10. 테스트와 디버깅', link: { type: 'generated-index', slug: '/category/10-테스트와-디버깅', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/테스트와-디버깅/index' }] },
        { type: 'category', label: '11. 환경설정과 보안', link: { type: 'generated-index', slug: '/category/11-환경설정과-보안', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/환경설정과-보안/index' }] },
        { type: 'category', label: '12. 모니터링과 운영 인수인계', link: { type: 'generated-index', slug: '/category/12-모니터링과-운영-인수인계', description: '학습 내용과 시작 조건은 아래 주제 안내에서 확인하세요.' }, items: [{ type: 'ref', id: 'tutorial/모니터링과-운영인수인계/index' }] }
    ],
    twelvefactorSidebar: [{ type: 'autogenerated', dirName: 'twelvefactor' }],
};

export default sidebars;
